// This file is auto-generated by Lovable. Do not modify it.

import { createLovableAuth } from "@lovable.dev/cloud-auth-js";
import { supabase, isSupabaseConfigured } from "../supabase/client";

const lovableAuth = createLovableAuth({});

type SignInOptions = {
  redirect_uri?: string;
  extraParams?: Record<string, string>;
};

export const lovable = {
  /** Whether Google/Apple OAuth can be used (Supabase must be configured) */
  isOAuthAvailable: isSupabaseConfigured,
  auth: {
    signInWithOAuth: async (provider: "google" | "apple", opts?: SignInOptions) => {
      if (!isSupabaseConfigured || !supabase) {
        return { error: new Error("Google Sign-In requires Supabase (VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY) to be set.") };
      }
      const result = await lovableAuth.signInWithOAuth(provider, {
        redirect_uri: opts?.redirect_uri,
        extraParams: {
          ...opts?.extraParams,
        },
      });

      if (result.redirected) {
        return result;
      }

      if (result.error) {
        return result;
      }

      try {
        await supabase.auth.setSession(result.tokens);
      } catch (e) {
        return { error: e instanceof Error ? e : new Error(String(e)) };
      }
      return result;
    },
  },
};
